kind: pipeline
type: docker
name: greeting
platform:
  os: linux
  arch: arm64

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  - echo "hi there step 2" > message.txt

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  - cat message.txt